<a href="https://colab.research.google.com/github/Ravurumadhuri/numpy-and-pandas/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Numpy




In [ ]:
import numpy as np


Array Creation Functions

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.zeros((2,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c = np.ones((2,2))
print(c)

[[1. 1.]
 [1. 1.]]


In [ ]:
d = np.arange(1, 10, 2)
print(d)

[1 3 5 7 9]


In [ ]:
e = np.linspace(1, 5, 4)
print(e)


[1.         2.33333333 3.66666667 5.        ]


In [ ]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
g = np.full((2,2), 7)
print(g)

[[7 7]
 [7 7]]


In [ ]:
h = np.empty((2,2))
print(h)

[[1.52230116e-315 0.00000000e+000]
 [4.94065646e-324 6.78159006e-310]]


2. Arithmetic Operations

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a,b)


[10 20 30] [1 2 3]


In [ ]:
print(np.add(a,b))

[11 22 33]


In [ ]:
print(np.subtract(a,b))

[ 9 18 27]


In [ ]:
print(np.multiply(a,b))

[10 40 90]


In [ ]:
print(np.divide(a,b))

[10. 10. 10.]


In [ ]:
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558]


In [ ]:
print(np.power(a,b))

[   10   400 27000]


In [ ]:
print(np.mod(a, 3))


[1 2 0]


In [ ]:
print(np.clip(a, 15, 25))

[15 20 25]


Statistical Operations

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
print(np.mean(arr))

25.0


In [ ]:
print(np.median(arr))

25.0


In [ ]:
print(np.std(arr))

11.180339887498949


In [ ]:
print(np.var(arr))

125.0


In [ ]:
print(np.min(arr))

10


In [ ]:
print(np.max(arr))

40


In [ ]:
print(np.percentile(arr, 50))

25.0


In [ ]:
print(np.average(arr, weights=[1,1,1,3]))


30.0


In [ ]:
arr = np.array([3, 5, 7])
print(arr)

[3 5 7]


In [ ]:
print(np.sum(arr))

15


In [ ]:
print(np.prod(arr))

105


In [ ]:
print(np.cumsum(arr))

[ 3  8 15]


In [ ]:
print(np.cumprod(arr))

[  3  15 105]


In [ ]:
print(np.argmax(arr))

2


In [ ]:
print(np.argmin(arr))

0


In [ ]:
print(np.all([True, True]))

True


In [ ]:
print(np.any([True, False]))

True


Linear Algebra(Matrix Operations)

In [ ]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [ ]:
print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [ ]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(np.linalg.det(A))

-2.0000000000000004


In [ ]:
print(np.linalg.eig(A))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
print(np.linalg.norm(A))

5.477225575051661


In [ ]:
Q, R = np.linalg.qr(A)

print("Q =\n", Q)
print("R =\n", R)

Q =
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R =
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [ ]:
U, S, VT = np.linalg.svd(A)

print("U =\n", U)
print("Singular Values =\n", S)
print("V^T =\n", VT)

U =
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values =
 [5.4649857  0.36596619]
V^T =
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


Random Module(np.random)

In [ ]:
a = np.random.rand(3)
b = np.random.rand(2, 3)
print(a)
print(b)



[0.77132064 0.02075195 0.63364823]
[[0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]]


In [ ]:
x = np.random.randint(10)              # Random int between 0 and 9
y = np.random.randint(5, 20, size=4)   # 4 random ints between 5 and 19
print(x)
print(y)

8
[11  9  8  5]


In [ ]:
normal_data = np.random.normal(50, 10, 5)
print(normal_data)

[44.65205473 60.32871136 48.63764248 51.76373075 53.10850735]


In [ ]:
items = [10, 20, 30, 40, 50]
choice = np.random.choice(items, size=3)
print(choice)


[40 20 50]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[4 3 5 1 2]


In [ ]:
np.random.seed(10)
print(np.random.rand(3))
np.random.seed(10)
print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]
[0.77132064 0.02075195 0.63364823]


In [54]:
uniform_data = np.random.uniform(5, 15, size=4)
print(uniform_data)

[12.48803883  9.98507012  7.24796646  6.98062865]


In [55]:
poisson_data = np.random.poisson(lam=4, size=6)
print(poisson_data)

[2 2 8 5 6 3]


Array Manipulation

In [57]:
a = np.array([[1,2],[3,4]])

In [58]:
print(np.reshape(a, (4,)))

[1 2 3 4]


In [59]:
print(a.flatten())

[1 2 3 4]


In [60]:
print(a.transpose())

[[1 3]
 [2 4]]


In [61]:
print(np.expand_dims(a, axis=0))

[[[1 2]
  [3 4]]]


In [63]:
print(np.squeeze(np.array([[[5]]])))

5


In [64]:
print(np.hstack([a, a]))

[[1 2 1 2]
 [3 4 3 4]]


In [65]:
print(np.vstack([a, a]))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [66]:
print(np.ravel(a))

[1 2 3 4]


In [68]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [69]:
print(np.where(arr > 25))

(array([2, 3]),)


In [70]:
print(np.take(arr, [0, 2]))

[10 30]


In [71]:
print(np.unique([1, 2, 2, 3]))

[1 2 3]


In [72]:
print(np.nonzero([1, 0, 3]))

(array([0, 2]),)


In [73]:
print(np.argsort(arr))

[0 1 2 3]


In [74]:
print(np.split(arr, 2))

[array([10, 20]), array([30, 40])]


In [75]:
print(np.flip(arr))

[40 30 20 10]


In [76]:
print(np.roll(arr, 1))

[40 10 20 30]


In [77]:
print(np.roll(arr, 1))

[40 10 20 30]
