<a href="https://colab.research.google.com/github/Ravurumadhuri/numpy-and-pandas/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Numpy




In [2]:
import numpy as np


Array Creation Functions

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
b = np.zeros((2,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
c = np.ones((2,2))
print(c)

[[1. 1.]
 [1. 1.]]


In [7]:
d = np.arange(1, 10, 2)
print(d)

[1 3 5 7 9]


In [9]:
e = np.linspace(1, 5, 4)
print(e)


[1.         2.33333333 3.66666667 5.        ]


In [10]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
g = np.full((2,2), 7)
print(g)

[[7 7]
 [7 7]]


In [3]:
h = np.empty((2,2))
print(h)

[[1.52230116e-315 0.00000000e+000]
 [4.94065646e-324 6.78159006e-310]]


2. Arithmetic Operations

In [10]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a,b)


[10 20 30] [1 2 3]


In [5]:
print(np.add(a,b))

[11 22 33]


In [6]:
print(np.subtract(a,b))

[ 9 18 27]


In [7]:
print(np.multiply(a,b))

[10 40 90]


In [8]:
print(np.divide(a,b))

[10. 10. 10.]


In [11]:
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558]


In [12]:
print(np.power(a,b))

[   10   400 27000]


In [13]:
print(np.mod(a, 3))


[1 2 0]


In [15]:
print(np.clip(a, 15, 25))

[15 20 25]


Statistical Operations

In [16]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [17]:
print(np.mean(arr))

25.0


In [18]:
print(np.median(arr))

25.0


In [24]:
print(np.std(arr))

11.180339887498949


In [23]:
print(np.var(arr))

125.0


In [22]:
print(np.min(arr))

10


In [21]:
print(np.max(arr))

40


In [20]:
print(np.percentile(arr, 50))

25.0


In [19]:
print(np.average(arr, weights=[1,1,1,3]))


30.0


In [25]:
arr = np.array([3, 5, 7])
print(arr)

[3 5 7]


In [26]:
print(np.sum(arr))

15


In [27]:
print(np.prod(arr))

105


In [28]:
print(np.cumsum(arr))

[ 3  8 15]


In [29]:
print(np.cumprod(arr))

[  3  15 105]


In [30]:
print(np.argmax(arr))

2


In [31]:
print(np.argmin(arr))

0


In [32]:
print(np.all([True, True]))

True


In [33]:
print(np.any([True, False]))

True


Linear Algebra(Matrix Operations)

In [34]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [35]:
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [36]:
print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [37]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
print(np.linalg.det(A))

-2.0000000000000004


In [39]:
print(np.linalg.eig(A))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [40]:
print(np.linalg.norm(A))

5.477225575051661


In [41]:
Q, R = np.linalg.qr(A)

print("Q =\n", Q)
print("R =\n", R)

Q =
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R =
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [42]:
U, S, VT = np.linalg.svd(A)

print("U =\n", U)
print("Singular Values =\n", S)
print("V^T =\n", VT)

U =
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values =
 [5.4649857  0.36596619]
V^T =
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


Random Module(np.random)

In [47]:
a = np.random.rand(3)
b = np.random.rand(2, 3)
print(a)
print(b)



[0.77132064 0.02075195 0.63364823]
[[0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]]


In [48]:
x = np.random.randint(10)              # Random int between 0 and 9
y = np.random.randint(5, 20, size=4)   # 4 random ints between 5 and 19
print(x)
print(y)

8
[11  9  8  5]
