<a href="https://colab.research.google.com/github/Ravurumadhuri/numpy-and-pandas/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Numpy




In [ ]:
import numpy as np


Array Creation Functions

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.zeros((2,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c = np.ones((2,2))
print(c)

[[1. 1.]
 [1. 1.]]


In [ ]:
d = np.arange(1, 10, 2)
print(d)

[1 3 5 7 9]


In [ ]:
e = np.linspace(1, 5, 4)
print(e)


[1.         2.33333333 3.66666667 5.        ]


In [ ]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
g = np.full((2,2), 7)
print(g)

[[7 7]
 [7 7]]


In [ ]:
h = np.empty((2,2))
print(h)

[[1.52230116e-315 0.00000000e+000]
 [4.94065646e-324 6.78159006e-310]]


2. Arithmetic Operations

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a,b)


[10 20 30] [1 2 3]


In [ ]:
print(np.add(a,b))

[11 22 33]


In [ ]:
print(np.subtract(a,b))

[ 9 18 27]


In [ ]:
print(np.multiply(a,b))

[10 40 90]


In [ ]:
print(np.divide(a,b))

[10. 10. 10.]


In [ ]:
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558]


In [ ]:
print(np.power(a,b))

[   10   400 27000]


In [ ]:
print(np.mod(a, 3))


[1 2 0]


In [ ]:
print(np.clip(a, 15, 25))

[15 20 25]


Statistical Operations

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
print(np.mean(arr))

25.0


In [ ]:
print(np.median(arr))

25.0


In [ ]:
print(np.std(arr))

11.180339887498949


In [ ]:
print(np.var(arr))

125.0


In [ ]:
print(np.min(arr))

10


In [ ]:
print(np.max(arr))

40


In [ ]:
print(np.percentile(arr, 50))

25.0


In [ ]:
print(np.average(arr, weights=[1,1,1,3]))


30.0


In [ ]:
arr = np.array([3, 5, 7])
print(arr)

[3 5 7]


In [ ]:
print(np.sum(arr))

15


In [ ]:
print(np.prod(arr))

105


In [ ]:
print(np.cumsum(arr))

[ 3  8 15]


In [ ]:
print(np.cumprod(arr))

[  3  15 105]


In [ ]:
print(np.argmax(arr))

2


In [ ]:
print(np.argmin(arr))

0


In [ ]:
print(np.all([True, True]))

True


In [ ]:
print(np.any([True, False]))

True


Linear Algebra(Matrix Operations)

In [ ]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [ ]:
print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [ ]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(np.linalg.det(A))

-2.0000000000000004


In [ ]:
print(np.linalg.eig(A))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
print(np.linalg.norm(A))

5.477225575051661


In [ ]:
Q, R = np.linalg.qr(A)

print("Q =\n", Q)
print("R =\n", R)

Q =
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R =
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [ ]:
U, S, VT = np.linalg.svd(A)

print("U =\n", U)
print("Singular Values =\n", S)
print("V^T =\n", VT)

U =
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values =
 [5.4649857  0.36596619]
V^T =
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


Random Module(np.random)

In [ ]:
a = np.random.rand(3)
b = np.random.rand(2, 3)
print(a)
print(b)



[0.77132064 0.02075195 0.63364823]
[[0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]]


In [ ]:
x = np.random.randint(10)              # Random int between 0 and 9
y = np.random.randint(5, 20, size=4)   # 4 random ints between 5 and 19
print(x)
print(y)

8
[11  9  8  5]


In [ ]:
normal_data = np.random.normal(50, 10, 5)
print(normal_data)

[44.65205473 60.32871136 48.63764248 51.76373075 53.10850735]


In [ ]:
items = [10, 20, 30, 40, 50]
choice = np.random.choice(items, size=3)
print(choice)


[40 20 50]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[4 3 5 1 2]


In [ ]:
np.random.seed(10)
print(np.random.rand(3))
np.random.seed(10)
print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]
[0.77132064 0.02075195 0.63364823]


In [ ]:
uniform_data = np.random.uniform(5, 15, size=4)
print(uniform_data)

[12.48803883  9.98507012  7.24796646  6.98062865]


In [ ]:
poisson_data = np.random.poisson(lam=4, size=6)
print(poisson_data)

[2 2 8 5 6 3]


Array Manipulation

In [ ]:
a = np.array([[1,2],[3,4]])

In [ ]:
print(np.reshape(a, (4,)))

[1 2 3 4]


In [ ]:
print(a.flatten())

[1 2 3 4]


In [ ]:
print(a.transpose())

[[1 3]
 [2 4]]


In [ ]:
print(np.expand_dims(a, axis=0))

[[[1 2]
  [3 4]]]


In [ ]:
print(np.squeeze(np.array([[[5]]])))

5


In [ ]:
print(np.hstack([a, a]))

[[1 2 1 2]
 [3 4 3 4]]


In [ ]:
print(np.vstack([a, a]))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [ ]:
print(np.ravel(a))

[1 2 3 4]


In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
print(np.where(arr > 25))

(array([2, 3]),)


In [ ]:
print(np.take(arr, [0, 2]))

[10 30]


In [ ]:
print(np.unique([1, 2, 2, 3]))

[1 2 3]


In [ ]:
print(np.nonzero([1, 0, 3]))

(array([0, 2]),)


In [ ]:
print(np.argsort(arr))

[0 1 2 3]


In [ ]:
print(np.split(arr, 2))

[array([10, 20]), array([30, 40])]


In [ ]:
print(np.flip(arr))

[40 30 20 10]


In [ ]:
print(np.roll(arr, 1))

[40 10 20 30]


In [ ]:
print(np.roll(arr, 1))

[40 10 20 30]


# Pandas

In [ ]:
import pandas as pd

In [ ]:
data = {"Name": ["Madhuri", "Dhana"], "Age": [23, 30]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0  Madhuri   23
1    Dhana   30


In [ ]:
s = pd.Series([1, 2, 3, 4])
print(s)


0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
df = pd.read_csv("sample_50_data.csv")
print(df)

    ID       Name  Age       City  Salary
0    1   Person_1   32    Chennai  109102
1    2   Person_2   50  Bengaluru   96252
2    3   Person_3   29    Chennai   78903
3    4   Person_4   27     Mumbai   32827
4    5   Person_5   40     Mumbai   86627
5    6   Person_6   42    Chennai   45270
6    7   Person_7   24  Bengaluru   39538
7    8   Person_8   26     Mumbai   58184
8    9   Person_9   26  Hyderabad   31833
9   10  Person_10   37  Bengaluru   99654
10  11  Person_11   33    Chennai  106323
11  12  Person_12   40  Bengaluru   78052
12  13  Person_13   22       Pune   85696
13  14  Person_14   27  Hyderabad   49935
14  15  Person_15   38  Hyderabad   93469
15  16  Person_16   49     Mumbai  101553
16  17  Person_17   48  Bengaluru   90785
17  18  Person_18   38    Chennai   36727
18  19  Person_19   35     Mumbai   57389
19  20  Person_20   24     Mumbai   32390
20  21  Person_21   21     Mumbai   60661
21  22  Person_22   41     Mumbai   79798
22  23  Person_23   38     Mumbai 

In [ ]:
df1=pd.read_excel("sample_50_data.xlsx")
print(df1)

    ID       Name  Age       City  Salary
0    1   Person_1   32    Chennai  109102
1    2   Person_2   50  Bengaluru   96252
2    3   Person_3   29    Chennai   78903
3    4   Person_4   27     Mumbai   32827
4    5   Person_5   40     Mumbai   86627
5    6   Person_6   42    Chennai   45270
6    7   Person_7   24  Bengaluru   39538
7    8   Person_8   26     Mumbai   58184
8    9   Person_9   26  Hyderabad   31833
9   10  Person_10   37  Bengaluru   99654
10  11  Person_11   33    Chennai  106323
11  12  Person_12   40  Bengaluru   78052
12  13  Person_13   22       Pune   85696
13  14  Person_14   27  Hyderabad   49935
14  15  Person_15   38  Hyderabad   93469
15  16  Person_16   49     Mumbai  101553
16  17  Person_17   48  Bengaluru   90785
17  18  Person_18   38    Chennai   36727
18  19  Person_19   35     Mumbai   57389
19  20  Person_20   24     Mumbai   32390
20  21  Person_21   21     Mumbai   60661
21  22  Person_22   41     Mumbai   79798
22  23  Person_23   38     Mumbai 

In [ ]:
dict_data = {"A": [1, 2, 3], "B": [10, 20, 30]}
df_dict = pd.DataFrame.from_dict(dict_data)
print(df_dict)

   A   B
0  1  10
1  2  20
2  3  30


In [ ]:
df_json = pd.read_json("sample_data.json")
print(df_json)

   id    name  age       city
0   1    Asha   25  Hyderabad
1   2    Ravi   28    Chennai
2   3   Kiran   32  Bengaluru
3   4   Meena   29     Mumbai
4   5  Vikram   35       Pune


In [ ]:
df_html = pd.read_html("https://www.w3schools.com/html/html_tables.asp")
print(df_html)

[                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy,           Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table


In [ ]:
import sqlite3

# Connect to SQLite database
conn = sqlite3.connect("database.db")
cursor = conn.cursor()

# Create employees table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    age INTEGER,
    city TEXT,
    salary REAL
)
""")

# Insert sample data
data = [
    (1, "Asha", 25, "Hyderabad", 45000),
    (2, "Ravi", 28, "Chennai", 52000),
    (3, "Kiran", 32, "Bengaluru", 61000),
    (4, "Meena", 29, "Mumbai", 58000),
    (5, "Vikram", 35, "Pune", 72000)
]

cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?, ?)", data)
conn.commit()

print("✅ Table created and data inserted!")


✅ Table created and data inserted!


In [ ]:
import pandas as pd
conn = sqlite3.connect("database.db")
df_sql = pd.read_sql("SELECT * FROM employees", conn)
print(df_sql)


   id    name  age       city   salary
0   1    Asha   25  Hyderabad  45000.0
1   2    Ravi   28    Chennai  52000.0
2   3   Kiran   32  Bengaluru  61000.0
3   4   Meena   29     Mumbai  58000.0
4   5  Vikram   35       Pune  72000.0


Data operations

In [ ]:
print(df.head())

   ID      Name  Age       City  Salary
0   1  Person_1   32    Chennai  109102
1   2  Person_2   50  Bengaluru   96252
2   3  Person_3   29    Chennai   78903
3   4  Person_4   27     Mumbai   32827
4   5  Person_5   40     Mumbai   86627


In [ ]:
print(df.tail())

    ID       Name  Age       City  Salary
45  46  Person_46   32  Bengaluru   74928
46  47  Person_47   42    Chennai  104948
47  48  Person_48   22     Mumbai   43317
48  49  Person_49   48    Chennai   71384
49  50  Person_50   29     Mumbai   79043


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      50 non-null     int64 
 1   Name    50 non-null     object
 2   Age     50 non-null     int64 
 3   City    50 non-null     object
 4   Salary  50 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 2.1+ KB
None


In [ ]:
print(df.describe())

             ID        Age         Salary
count  50.00000  50.000000      50.000000
mean   25.50000  35.200000   73050.220000
std    14.57738   8.896227   24492.995376
min     1.00000  21.000000   30625.000000
25%    13.25000  27.000000   56975.000000
50%    25.50000  36.000000   76490.000000
75%    37.75000  42.000000   92798.000000
max    50.00000  50.000000  115745.000000


In [ ]:
print(df.shape)

(50, 5)


In [ ]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'City', 'Salary'], dtype='object')


In [ ]:
print(df.dtypes)

ID         int64
Name      object
Age        int64
City      object
Salary     int64
dtype: object


In [ ]:
print(df.memory_usage())

Index     132
ID        400
Name      400
Age       400
City      400
Salary    400
dtype: int64


#Data Selection

In [2]:
import pandas as pd

df = pd.read_csv("sample_50_data.csv")

In [5]:
print(df.iloc[0, 1])

Person_1


In [6]:
print(df.iloc[0:5, 1:4])

       Name  Age       City
0  Person_1   32    Chennai
1  Person_2   50  Bengaluru
2  Person_3   29    Chennai
3  Person_4   27     Mumbai
4  Person_5   40     Mumbai


In [8]:
print(df.loc[10, "Name"])

Person_11


In [9]:
print(df.loc[5:10, ["Name", "City", "Salary"]])

         Name       City  Salary
5    Person_6    Chennai   45270
6    Person_7  Bengaluru   39538
7    Person_8     Mumbai   58184
8    Person_9  Hyderabad   31833
9   Person_10  Bengaluru   99654
10  Person_11    Chennai  106323


In [10]:
print(df.at[3, "City"])

Mumbai


In [11]:
print(df.iat[3, 2])

27


In [15]:
print(df.query("Salary > 90000"))
print("------------------------------------------------------")
print(df.query("City == 'Hyderabad'"))
print("------------------------------------------------------")
print(df.query("Age > 30 and Salary < 60000"))

    ID       Name  Age       City  Salary
0    1   Person_1   32    Chennai  109102
1    2   Person_2   50  Bengaluru   96252
9   10  Person_10   37  Bengaluru   99654
10  11  Person_11   33    Chennai  106323
14  15  Person_15   38  Hyderabad   93469
15  16  Person_16   49     Mumbai  101553
16  17  Person_17   48  Bengaluru   90785
22  23  Person_23   38     Mumbai  103190
23  24  Person_24   38    Chennai  115521
26  27  Person_27   27  Hyderabad   94322
28  29  Person_29   41  Hyderabad   90075
29  30  Person_30   25    Chennai   95562
35  36  Person_36   34    Chennai   97552
40  41  Person_41   37       Pune  115745
46  47  Person_47   42    Chennai  104948
------------------------------------------------------
    ID       Name  Age       City  Salary
8    9   Person_9   26  Hyderabad   31833
13  14  Person_14   27  Hyderabad   49935
14  15  Person_15   38  Hyderabad   93469
24  25  Person_25   48  Hyderabad   83925
26  27  Person_27   27  Hyderabad   94322
28  29  Person_29   4

In [16]:
print(df.filter(["Name", "Salary"]))

         Name  Salary
0    Person_1  109102
1    Person_2   96252
2    Person_3   78903
3    Person_4   32827
4    Person_5   86627
5    Person_6   45270
6    Person_7   39538
7    Person_8   58184
8    Person_9   31833
9   Person_10   99654
10  Person_11  106323
11  Person_12   78052
12  Person_13   85696
13  Person_14   49935
14  Person_15   93469
15  Person_16  101553
16  Person_17   90785
17  Person_18   36727
18  Person_19   57389
19  Person_20   32390
20  Person_21   60661
21  Person_22   79798
22  Person_23  103190
23  Person_24  115521
24  Person_25   83925
25  Person_26   40181
26  Person_27   94322
27  Person_28   30625
28  Person_29   90075
29  Person_30   95562
30  Person_31   64767
31  Person_32   56837
32  Person_33   66411
33  Person_34   47428
34  Person_35   82129
35  Person_36   97552
36  Person_37   89775
37  Person_38   78701
38  Person_39   73081
39  Person_40   65969
40  Person_41  115745
41  Person_42   35522
42  Person_43   62993
43  Person_44   63204
44  Person

In [17]:
print(df.filter(like="a"))

         Name  Salary
0    Person_1  109102
1    Person_2   96252
2    Person_3   78903
3    Person_4   32827
4    Person_5   86627
5    Person_6   45270
6    Person_7   39538
7    Person_8   58184
8    Person_9   31833
9   Person_10   99654
10  Person_11  106323
11  Person_12   78052
12  Person_13   85696
13  Person_14   49935
14  Person_15   93469
15  Person_16  101553
16  Person_17   90785
17  Person_18   36727
18  Person_19   57389
19  Person_20   32390
20  Person_21   60661
21  Person_22   79798
22  Person_23  103190
23  Person_24  115521
24  Person_25   83925
25  Person_26   40181
26  Person_27   94322
27  Person_28   30625
28  Person_29   90075
29  Person_30   95562
30  Person_31   64767
31  Person_32   56837
32  Person_33   66411
33  Person_34   47428
34  Person_35   82129
35  Person_36   97552
36  Person_37   89775
37  Person_38   78701
38  Person_39   73081
39  Person_40   65969
40  Person_41  115745
41  Person_42   35522
42  Person_43   62993
43  Person_44   63204
44  Person

In [18]:
print(df.sample(5))

    ID       Name  Age       City  Salary
46  47  Person_47   42    Chennai  104948
30  31  Person_31   47  Bengaluru   64767
18  19  Person_19   35     Mumbai   57389
27  28  Person_28   28    Chennai   30625
1    2   Person_2   50  Bengaluru   96252


In [19]:
print(df.select_dtypes(include="number"))

    ID  Age  Salary
0    1   32  109102
1    2   50   96252
2    3   29   78903
3    4   27   32827
4    5   40   86627
5    6   42   45270
6    7   24   39538
7    8   26   58184
8    9   26   31833
9   10   37   99654
10  11   33  106323
11  12   40   78052
12  13   22   85696
13  14   27   49935
14  15   38   93469
15  16   49  101553
16  17   48   90785
17  18   38   36727
18  19   35   57389
19  20   24   32390
20  21   21   60661
21  22   41   79798
22  23   38  103190
23  24   38  115521
24  25   48   83925
25  26   26   40181
26  27   27   94322
27  28   28   30625
28  29   41   90075
29  30   25   95562
30  31   47   64767
31  32   24   56837
32  33   26   66411
33  34   44   47428
34  35   45   82129
35  36   34   97552
36  37   41   89775
37  38   31   78701
38  39   27   73081
39  40   47   65969
40  41   37  115745
41  42   26   35522
42  43   47   62993
43  44   45   63204
44  45   46   74408
45  46   32   74928
46  47   42  104948
47  48   22   43317
48  49   48   71384


In [20]:
print(df.select_dtypes(include="object"))

         Name       City
0    Person_1    Chennai
1    Person_2  Bengaluru
2    Person_3    Chennai
3    Person_4     Mumbai
4    Person_5     Mumbai
5    Person_6    Chennai
6    Person_7  Bengaluru
7    Person_8     Mumbai
8    Person_9  Hyderabad
9   Person_10  Bengaluru
10  Person_11    Chennai
11  Person_12  Bengaluru
12  Person_13       Pune
13  Person_14  Hyderabad
14  Person_15  Hyderabad
15  Person_16     Mumbai
16  Person_17  Bengaluru
17  Person_18    Chennai
18  Person_19     Mumbai
19  Person_20     Mumbai
20  Person_21     Mumbai
21  Person_22     Mumbai
22  Person_23     Mumbai
23  Person_24    Chennai
24  Person_25  Hyderabad
25  Person_26  Bengaluru
26  Person_27  Hyderabad
27  Person_28    Chennai
28  Person_29  Hyderabad
29  Person_30    Chennai
30  Person_31  Bengaluru
31  Person_32       Pune
32  Person_33     Mumbai
33  Person_34     Mumbai
34  Person_35  Hyderabad
35  Person_36    Chennai
36  Person_37  Bengaluru
37  Person_38  Hyderabad
38  Person_39  Hyderabad


In [23]:
print(df.iloc[0:3, 0:2])
print("------------------------------------------------------")
print(df.loc[5:8, ["Name", "City"]])
print("------------------------------------------------------")
print(df.query("City == 'Pune'"))


   ID      Name
0   1  Person_1
1   2  Person_2
2   3  Person_3
------------------------------------------------------
       Name       City
5  Person_6    Chennai
6  Person_7  Bengaluru
7  Person_8     Mumbai
8  Person_9  Hyderabad
------------------------------------------------------
    ID       Name  Age  City  Salary
12  13  Person_13   22  Pune   85696
31  32  Person_32   24  Pune   56837
40  41  Person_41   37  Pune  115745


In [24]:

print(df.sample(3))
print("------------------------------------------------------")
print(df.select_dtypes(include="number"))

    ID       Name  Age       City  Salary
49  50  Person_50   29     Mumbai   79043
39  40  Person_40   47    Chennai   65969
28  29  Person_29   41  Hyderabad   90075
------------------------------------------------------
    ID  Age  Salary
0    1   32  109102
1    2   50   96252
2    3   29   78903
3    4   27   32827
4    5   40   86627
5    6   42   45270
6    7   24   39538
7    8   26   58184
8    9   26   31833
9   10   37   99654
10  11   33  106323
11  12   40   78052
12  13   22   85696
13  14   27   49935
14  15   38   93469
15  16   49  101553
16  17   48   90785
17  18   38   36727
18  19   35   57389
19  20   24   32390
20  21   21   60661
21  22   41   79798
22  23   38  103190
23  24   38  115521
24  25   48   83925
25  26   26   40181
26  27   27   94322
27  28   28   30625
28  29   41   90075
29  30   25   95562
30  31   47   64767
31  32   24   56837
32  33   26   66411
33  34   44   47428
34  35   45   82129
35  36   34   97552
36  37   41   89775
37  38   31   787