<a href="https://colab.research.google.com/github/Ravurumadhuri/numpy-and-pandas/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Numpy




In [1]:
import numpy as np


Array Creation Functions

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
b = np.zeros((2,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
c = np.ones((2,2))
print(c)

[[1. 1.]
 [1. 1.]]


In [7]:
d = np.arange(1, 10, 2)
print(d)

[1 3 5 7 9]
